"""initial

Revision ID: 0001_initial
Revises:
"""
from alembic import op
import sqlalchemy as sa
import agentwatch.db.types


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_runs_source'), ['source'], unique=False)

    op.create_table('raw_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_json', agentwatch.db.types.JSONB(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_artifacts_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_raw_artifacts_source'), ['source'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_artifact_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_source'), ['source'], unique=False)

    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('relevance', sa.String(length=50), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('evidence_quality', sa.String(length=50), nullable=True),
    sa.Column('autonomy_level', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifications_incident_id'), ['incident_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('corrected_fields', agentwatch.db.types.JSONB(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_classification_id'), ['classification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_classification_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classifications_incident_id'))

    op.drop_table('classifications')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_source'))
        batch_op.drop_index(batch_op.f('ix_incidents_content_hash'))

    op.drop_table('incidents')
    with op.batch_alter_table('raw_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_artifacts_source'))
        batch_op.drop_index(batch_op.f('ix_raw_artifacts_content_hash'))

    op.drop_table('raw_artifacts')
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_runs_source'))

    op.drop_table('collection_runs')
    # ### end Alembic commands ###
